V2.0

diff --git a/bin/zbx,dev b/bin/zbx,dev
--- a/bin/zbx,dev
+++ b/bin/zbx,dev
@@ -1,103 +1,97 @@
 #!/bin/bash
+### Usage: $0 <zref?>
+## This wraps for git worktree workflow.
+## Example:
+##         $0
+##         # This means I want to jump on review.
+##         # All remote is listed to choose for branch.
+##         # Chosen branch is added to worktree and upstream is set.
+##         # Multiselect is possible (use tab).
+## Example:
+##         $0 ZBX-123-4.4
+##         # This means I want to start work on fresh feature.
+##         # First branch name is validated.
+##         # Then you choose what branch it is based on.
+##         # Then branch is created and pushed.
+##         # Chosen branch is added to worktree and upstream is set.
+## Optionally worktree path is put into "z" jump-path helper (see .env).
+##~
 source zbx-script-header
 
-### Main dev entry.
-### Usage: $0 <ZREF?> [--SWITCH..]
-# Docs {{{1
-##
-## <zref>: Possible values.
-## |  lowercase "m"  - master
-## |  a dot "."      - a menu to choose any remote ref in fzf
-## |  4.4            - refs/heads/release/4.4
-## |  "ZBX-1000-4.0" - refs/heads/feature/<CREATED-OR-UPDATED>
-## |  <not-given>    - determined from PWD or error
-##
-## <switches>:
-## | if create happens - auto enabled database and generate config flag
-##
-## If run without arguments, gives system overview information.
+create-feature(){
+    cd "$WORKTREE/master"
+    git worktree add --no-track -f -b "$1" "$WORKTREE/$1" "$2"
+    cd $WORKTREE/$1
+    git push origin HEAD
 
-# Ref {{{1
-case $1 in
-'') zbx-script-info && exit;;
-. ) REF=$(echo "$(ls-remote)" | fzf);shift;;
-m*) REF=master;shift;;
--*) REF=$(zbx-util-guess-ref);;
-* ) REF=$(zbx-util-validate-zref $1);shift;;
-esac
+    return $?
+}
 
-[ -z "$REF" ] && exit 2;
+pull-feature(){
+    if [ ! -d "$WORKTREE/$1" ];then
+        cd "$WORKTREE/master"
+        git worktree add -f "$WORKTREE/$1" "$1"
+        cd $WORKTREE/$1
+        git branch --set-upstream-to "origin/$1"
+    else
+        >&2 echo "Cannot add worktree, $WORKTREE/$1 already exists!"
+        return 6
+    fi
 
-NOTIF=
-CODEPATH="$WORKTREE/$REF"
-ALLOW_CREATE=${REF##release*}
-REMOTE_EXISTS=$(echo "$(ls-remote)" | ag "^$REF$" | cat)
+    return $?
+}
 
-if [ -z $ALLOW_CREATE ] && [ -z $REMOTE_EXISTS ];then
-    >&2 echo ref: $REF not found in remote. Exiting.
-    exit 3
-fi
+update-jumpfile(){
+    if [ -z $Z_JUMP_FILE ];then
+        return 0
+    fi
 
-if [ ! -z $Z_JUMP_FILE ];then
     if [ -f $Z_JUMP_FILE ];then
-        echo "$CODEPATH/frontends/php|1|$(date +%s)" >> $Z_JUMP_FILE
+        entry="$WORKTREE/$1/frontends/php|1|$(date +%s)"
+        echo "$entry" >> $Z_JUMP_FILE
     else
         >&2 echo $Z_JUMP_FILE not found
     fi
-fi
+}
 
-# Git {{{1
-cd "$WORKTREE/master" && git fetch
+validate-create(){
+    REF=$(zbx-util-validate-zref $1)
+    [ -z "$REF" ] && return 2
+    [ -z "${REF##release*}" ] && >&2 echo "Not allowed to create $REF" && return 3
+    [ -z "${REF##master}" ] && >&2 echo "Not allowed to create $REF" && return 4
 
-if [ $ALLOW_CREATE ] && [ -z $REMOTE_EXISTS ];then
-    BASEREF="origin/$(\
-        echo "$(ls-remote)" | fzf \
-            --header "About to create '$REF'!" \
-            --prompt "Choose which REF will '$REF' be based on: > " \
-            --query "release"
-    )"
+    REMOTE_EXISTS=$(ls-remote | ag "^$REF$")
+    [ ! -z "$REMOTE_EXISTS" ] && \
+        >&2 echo "$REF is already created in remote." \
+        && return 5
 
-    git worktree add --no-track -f -b "$REF" "$CODEPATH" "$BASEREF"
-    cd $CODEPATH
-    git push origin HEAD
-    zbx+config
-    FLAG_DB=1
-    FLAG_WEB=1
-    FLAG_CONF=1
-    NOTIF="Created $REF"
+    echo -n $REF
+
+    return 0
+}
+
+set -e
+# pull-feature
+if [ -z "$1" ];then
+    for REF in $(ls-remote | fzf \
+        --header "git ls-remote '$GITREMOTE'" \
+        --prompt "Choose branches to be added to your worktree > " \
+        --query "feature/" \
+        --multi)
+    do
+        pull-feature $REF | zbx-util-color -H "Pulling '$REF'"
+        update-jumpfile $REF
+    done
+# create-feature
 else
-    echo updating $REF for you...
-    if [ ! -d "$CODEPATH" ];then
-        FLAG_DB=1
-        FLAG_WEB=1
-        FLAG_CONF=1
-        git worktree add -f "$CODEPATH" "$REF"
-        NOTIF="Added $REF"
-    else
-        NOTIF="Updated $REF"
-    fi
+    REF=$(validate-create $1)
+
+    BASEREF="origin/$(ls-remote | fzf \
+        --header "About to create '$REF'!" \
+        --prompt "Choose which REF will '$REF' be based on: > " \
+        --query "release")"
+
+    create-feature $REF $BASEREF \
+        | zbx-util-color -H "Creating new '$REF' based on '$BASEREF' in '$GITREMOTE'"
+    update-jumpfile $REF
 fi
-
-cd $CODEPATH
-git branch --set-upstream-to "origin/$REF"
-
-# Switches {{{1
-while [[ $# > 0 ]];do case $1 in
-    #- this will build fresh data.sql and recreate database (ref-named)
-    -D  | --database) FLAG_DB=1 ;;
-    #- this will build fresh data.sql and recreate database (ref-named)
-    -Ds | --database-selenium) FLAG_DB=1 ;;
-    #- build zabbix server and agent
-    -S  | --srv) FLAG_SRV=1 ;;
-esac;shift;done
-
-[ $FLAG_DB ] && zbx,box -C "$REF"
-[ $FLAG_SRV ] && zbx,box -S "$REF"
-[ $FLAG_CONF ] && zbx+config "$REF"
-[ $FLAG_WEB ] && zbx,web "$REF"
-
-zbx,api-seeds
-
-[ ! -z "$NOTIF" ] && notify-send "$NOTIF"
-
-# vim: fdm=marker
